### PR TITLE
New USBD Stack!

### PR DESCRIPTION
**Pull request by kuldeepdhaka**
Feature:
- Transfer based API
- No per packet handling for application
- High level API
- Generate header file using script.
- Support for String descriptor without any user work
- Configuration support ([optional] in init() via application)
  - Number of endpoint (usecase: Reduce consumption of memory by using less registers)
  - Internal memory (usecase: CAN/USB shared buffer)
  - External PHY selection
  - VBUS detection enable/disable
  - Speed selection

Note:
- Support for LM4F USB device dropped
- MSC rewrite (and tested for working)
- Removed redudent DWC_OTG headers
- ucdef - header generator (data embedded in header file)
- Remove all redundent DWC OTG register defination.
- Consistant code
- Get rid of REBASE_FIFO macro. (Thanks to @jhoenicke)
- Use memcpy() instead of manually copying in DWC_OTG
- Automatically turn on clock for STM32 OTG HS/FS clock (Thanks to @karlp)
- Remove extra SET, TOG, CLR macro for ST FSDEV

Warning:
- If debugging is turn-on for STM32F0, unable to communicate properly.
  probably: it is alot of time to output the log via USART.

Tested:
- STM32F072
  - Internal PHY, FULL Speed, USBD_STM32_FSDEV_V2
- EFM32LG
  - Internal PHY, FULL Speed, USBD_EFM32LG
- STM32F407
  - Internal PHY, FULL Speed, USBD_STM32_OTG_FS
- STM32F746
  - Internal PHY, FULL Speed, USBD_STM32_OTG_FS
  - External PHY, FULL Speed, USBD_STM32_OTG_HS
- STM32F769
  - External PHY, HIGH Speed, USBD_STM32_OTG_HS
  - External PHY, FULL Speed, USBD_STM32_OTG_HS

### CODE REVIEW

**Comment by kuldeepdhaka** [comment]
Examples: https://github.com/insane-adding-machines/unicore-mx-examples/pull/7

**Comment by danielinux** [comment]
Can you prepare a PR for https://github.com/insane-adding-machines/frosted for the adaptations on the new API?

**Comment by brabo** [comment]
@kuldeepdhaka hiya! any update on @danielinux question? :)

**Comment by kuldeepdhaka** [comment]
@brabo @danielinux Yes, we will have frosted support too.
Im atm trying to use the new stack in box0-v5-firmware.
That will finally make sure that this stack is usable.

**Comment by brabo** [comment]
@kuldeepdhaka super! :+1:

**Comment by kuldeepdhaka** [comment]
Note: Made a few changes and we can consider this somewhat final.

**Comment by brabo** [comment]
Merging this finally! Thanks a lot @kuldeepdhaka!!

**Pull request merged**
